### PR TITLE
[GPUI][BUG] The order of messages in .pol files

### LINKED ISSUE #79: [GPUI][BUG] The order of messages in .pol files
In accordance with https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-gpreg/57226664-ce00-4487-994e-a6b3820f3e49

Quote:
> - The Instruction elements MUST be processed in the order in which they occur, sequentially from the start of the Registry Policy message. The necessity of this is demonstrated by an example in which an Instruction requires a database value to be set to 1 and another Instruction requires it to be set to 0. Depending on the order in which those instructions are performed, the final value will be either 1 or 0. To ensure predictable operation, Instructions MUST be performed sequentially, beginning with the first Instruction in the Registry Policy message.

However, PRegParser does not preserve the order and does not process/write commands.

## BackLog 
- [x] In [src/plugins/pol/parser.h](https://github.com/august-alt/gpui/blob/master/src/plugins/pol/parser.h) change the type of `PolicyTree` so that it preserves the order of instructions
```cpp
typedef std::unordered_map<std::string, std::unordered_map<std::string, std::vector<PolicyInstruction>>> PolicyTree;
``` 
- [x] Fix reading/writing to this PolicyTree in 4 places according to previous changes: when reading/writing to PRegParser [src/plugins/pol/parser.h](https://github.com/august-alt/gpui/blob/master/src/plugins/pol/parser.h), and when converting from/to PolicyTree [src/plugins/pol/polformat.cpp](https://github.com/august-alt/gpui/blob/master/src/plugins/pol/polformat.cpp)

### PR DESCRIPTION
**Pull request by kiper220-alt**
fix #79

### CODE REVIEW

File: src/plugins/pol/parser.h [hunk 1]
```diff
@@ -70,20 +70,20 @@ typedef struct PolicyInstruction
 {
     inline bool operator==(const PolicyInstruction &other) const
     {
-        return type == other.type && data == other.data;
+        return key == other.key && key == other.key && value == other.value && data == other.data;
```
Comment (august-alt) [inline src/plugins/pol/parser.h:73]: Remove second `key == other.key`.

Comment (august-alt) [reply src/plugins/pol/parser.h:73]: We should compare type here.

File: src/plugins/pol/polformat.cpp [hunk 2]
```diff
@@ -240,14 +233,10 @@ bool PolFormat::read(std::istream &input, io::RegistryFile *file)
...
-        for (const auto &[value, array] : record) {
-            for(const auto &entry : array) {
-                auto registryEntry = RegistryEntryAdapter::create(entry, key, value);
-                if (registryEntry.get()) {
-                    registry->registryEntries.push_back(std::move(registryEntry));
-                }
-            }
+    for(const auto &entry : result.instructions) {
+        auto registryEntry = RegistryEntryAdapter::create(entry, entry.key, entry.value);
+        if (registryEntry.get()) {
```
Comment (august-alt) [inline src/plugins/pol/polformat.cpp:238]: If I recall correctly we can use `if (registryEntry)` here.

**Review by august-alt — CHANGES_REQUESTED** [review]

**Review by august-alt — APPROVED** [review]
